# Generated by Django 4.0.1 on 2023-09-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_no', models.IntegerField()),
                ('description', models.TextField()),
                ('ques_url', models.URLField()),
                ('ans_url', models.URLField()),
                ('ques_heading', models.TextField()),
                ('ques_image', models.ImageField(upload_to='')),
                ('ans_image', models.ImageField(upload_to='')),
                ('ans_second_image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.category')),
            ],
        ),
    ]
