# Generated by Django 4.0.1 on 2023-09-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_urls_alter_photo_ans_second_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='url_link',
            field=models.URLField(default='https://leetcode.com/arinutkarsh55/'),
        ),
    ]
